import json
from pathlib import Path
import unittest


ROOT = Path(__file__).parents[1]


class ProjectContractTests(unittest.TestCase):
    def test_manifest_points_to_existing_skill_directory(self):
        manifest = json.loads((ROOT / ".codex-plugin" / "plugin.json").read_text(encoding="utf-8"))
        self.assertEqual(manifest["name"], "semantic-mesh-restorer-next")
        self.assertTrue((ROOT / manifest["skills"]).is_dir())

    def test_addon_uses_side_by_side_namespace(self):
        operators = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "operators.py").read_text(encoding="utf-8")
        self.assertIn('bl_idname = "smrn.mark_surface"', operators)
        self.assertNotIn('bl_idname = "smr.', operators)

    def test_marker_supports_continuous_drag_brushing(self):
        operators = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "operators.py").read_text(encoding="utf-8")
        raycast = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "raycast.py").read_text(encoding="utf-8")
        self.assertIn('event.type == "MOUSEMOVE"', operators)
        self.assertIn("def _paint_segment", operators)
        self.assertIn("self._painting = True", operators)
        self.assertIn("dragging=True", operators)
        self.assertIn("def brush_scene_hits", raycast)
        self.assertIn("def brush_object_hits", raycast)
        self.assertIn("def object_hit_at", raycast)
        self.assertIn("_brush_disc_offsets(radius_px)", raycast)
        self.assertIn('hit["hit_object_name"] != anchor_object', raycast)
        self.assertIn("self._marked_faces", operators)
        self.assertIn("self._fingerprints", operators)
        self.assertIn("self._stroke_object_name", operators)
        self.assertIn("brush_object_hits", operators)
        self.assertIn("brush_object_stroke_hits", operators)
        self.assertIn("append_marks", operators)
        self.assertIn("rebuild_task_surface_overlays", operators)
        self.assertIn("smrn_batched_overlay", (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "overlay.py").read_text(encoding="utf-8"))
        self.assertNotIn("magnetic_radius = min(magnetic_radius, 4)", operators)

    def test_marker_has_role_specific_drag_erasers(self):
        operators = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "operators.py").read_text(encoding="utf-8")
        panel = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "panel.py").read_text(encoding="utf-8")
        self.assertIn('erase: bpy.props.BoolProperty(default=False)', operators)
        self.assertIn("replace_task_marks", operators)
        self.assertIn("_current_erase_removed", operators)
        self.assertIn('text="擦除绿色"', panel)
        self.assertIn('text="擦除红色"', panel)

    def test_marker_overlay_follows_visible_proxy_geometry(self):
        overlay = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "overlay.py").read_text(encoding="utf-8")
        self.assertIn('hit.get("raycast_object_name", "")', overlay)
        self.assertIn("geometry_obj.data.polygons", overlay)
        self.assertIn('overlay["smrn_raycast_object_name"] = geometry_obj.name', overlay)
        self.assertNotIn("world_vertices = [hit_obj.matrix_world @ hit_obj.data.vertices", overlay)

    def test_marker_buttons_reset_erase_mode_and_switch_in_one_click(self):
        operators = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "operators.py").read_text(encoding="utf-8")
        panel = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "panel.py").read_text(encoding="utf-8")
        self.assertIn("target.erase = False", panel)
        self.assertIn("exclude.erase = False", panel)
        sidebar_branch = operators.split("if self._over_sidebar(event.mouse_x, event.mouse_y):", 1)[1]
        sidebar_branch = sidebar_branch.split("self._painting = True", 1)[0]
        self.assertIn('return {"PASS_THROUGH"}', sidebar_branch)
        self.assertNotIn('return {"FINISHED"}', sidebar_branch)

    def test_legacy_helpers_are_excluded_from_raycast(self):
        scene_state = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "scene_state.py").read_text(encoding="utf-8")
        self.assertIn('obj.get("smr_annotation_only", False)', scene_state)
        self.assertIn('obj.get("smr_source_name", "")', scene_state)

    def test_unaccepted_candidates_cannot_steal_brush_hits(self):
        scene_state = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "scene_state.py").read_text(encoding="utf-8")
        raycast = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "raycast.py").read_text(encoding="utf-8")
        self.assertIn("def is_unaccepted_candidate_object", scene_state)
        self.assertIn('owner.name == CANDIDATE_COLLECTION_NAME', scene_state)
        self.assertIn('bool(obj.get("smrn_accepted", False))', scene_state)
        self.assertIn("is_unaccepted_candidate_object(obj)", raycast)
        self.assertIn("passthrough_objects", raycast)

    def test_panel_uses_lightweight_summary(self):
        panel = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "panel.py").read_text(encoding="utf-8")
        self.assertIn("marks_summary(scene)", panel)
        self.assertNotIn("load_marks(scene)", panel)

    def test_panel_defaults_to_one_click_workflow(self):
        panel = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "panel.py").read_text(encoding="utf-8")
        addon = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "__init__.py").read_text(encoding="utf-8")
        self.assertIn('text="重建绿色圆润原网面"', panel)
        self.assertIn('text="一键生成扶手候选"', panel)
        self.assertIn("if scene.smrn_show_advanced:", panel)
        self.assertIn('bpy.types.Scene.smrn_show_advanced = bpy.props.BoolProperty(', addon)
        self.assertIn("default=False", addon)
        advanced_section = panel.split("if scene.smrn_show_advanced:", 1)[1]
        self.assertIn('prop(scene, "smrn_rotational_segments"', advanced_section)
        self.assertIn('prop(scene, "smrn_handle_path_segments"', advanced_section)

    def test_chunked_versioned_storage_exists(self):
        storage = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "storage.py").read_text(encoding="utf-8")
        self.assertIn('DOCUMENT_KEY = "smrn_document_json"', storage)
        self.assertIn("CHUNK_SIZE = 128", storage)

    def test_rotational_feature_stays_non_destructive(self):
        adapter = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "rotational_blender.py").read_text(encoding="utf-8")
        self.assertIn('CANDIDATE_PREFIX = "SMRN_ROTATIONAL_CANDIDATE_"', adapter)
        self.assertIn("_commit_candidate(scene, obj)", adapter)
        self.assertIn("_semantic_rotational_faces(fit, source, targets)", adapter)
        self.assertIn("semantic_expansion", adapter)
        self.assertNotIn("remove_last_candidate(scene)\n    _model, candidates", adapter)
        self.assertIn("source_unchanged", (ROOT / "scripts" / "live_build_gate_test.py").read_text(encoding="utf-8"))
        self.assertNotIn("bpy.ops.object.delete", adapter)
        auto_thickness = adapter.split("def _auto_thickness", 1)[1].split("def _ring_point", 1)[0]
        self.assertIn("feature_scale * 0.18", auto_thickness)
        self.assertIn("radius * 0.04", auto_thickness)
        self.assertNotIn("radius * 0.08", auto_thickness)
        self.assertIn('"visible_surface_preserved": True', adapter)
        self.assertIn('"backing_direction": ("toward_axis"', adapter)

    def test_disconnected_rotational_marks_require_local_geometric_proof(self):
        adapter = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "rotational_blender.py").read_text(encoding="utf-8")
        self.assertIn("def _selected_weld_frame", adapter)
        self.assertIn("typical * 1.0e-5", adapter)
        self.assertIn("def _normal_derived_cylinder_rings", adapter)
        self.assertIn('"normal_axis_condition": condition', adapter)
        self.assertIn('"method": "normal_null_axis_projected_source_envelope_rings"', adapter)
        self.assertIn("unique_source_vertices_with_averaged_source_normals", adapter)
        self.assertIn("def _broad_arc_island_rings", adapter)
        self.assertIn("span < math.radians(160.0)", adapter)
        self.assertIn('"method": "broad_arc_two_plane_island_merge"', adapter)
        self.assertIn('"source_mesh_modified": False', adapter)
        self.assertIn('"whole_vehicle_search": False', adapter)

    def test_rotational_selection_rebuild_is_exact_and_local(self):
        adapter = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "rotational_blender.py").read_text(encoding="utf-8")
        operators = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "operators.py").read_text(encoding="utf-8")
        panel = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "panel.py").read_text(encoding="utf-8")
        self.assertIn("def build_selected_scene_candidate", adapter)
        self.assertIn('"selection_method": "exact_edit_mode_faces"', adapter)
        self.assertIn('"expanded_faces": 0', adapter)
        self.assertIn('"whole_vehicle_search": False', adapter)
        self.assertIn('"scope": ("exact_selected_faces_only"', adapter)
        self.assertIn("def _selected_rotational_faces", operators)
        self.assertIn("bmesh.from_edit_mesh", operators)
        self.assertIn("build_selected_scene_candidate", operators)
        self.assertIn('has_green_marks = int(mark_counts.get(TARGET_ROLE, 0)) > 0', operators)
        self.assertIn('if has_green_marks:', operators)
        self.assertLess(operators.index('if has_green_marks:'), operators.index('selected = _selected_rotational_faces(context)', operators.index('if has_green_marks:')))
        self.assertIn('bpy.ops.object.mode_set(mode="OBJECT")', operators)
        self.assertIn("现有语义标记保持不变", operators)
        self.assertIn('text="物体模式绿色刷选；重建原网面，不生成罩体"', panel)
        self.assertIn('text="重建绿色圆润原网面"', panel)
        self.assertIn('rebuild_rotational.mode = "rotational"', panel)
        self.assertIn('text="独立圆圈候选（不替换原网面）"', panel)
        self.assertIn('text="生成独立圆圈候选"', panel)
        self.assertIn('"确认独立圆圈（保留标记）"', panel)
        self.assertIn('def _envelope_profile', adapter)
        self.assertIn('def _analytic_envelope_profile', adapter)
        self.assertIn('"clearance_mode": "analytic_affine_outer_envelope"', adapter)
        self.assertIn('polygon.use_smooth = polygon.index in smooth_face_set', adapter)
        self.assertIn('obj.show_wire = False', adapter)
        self.assertGreater(
            panel.index('text="生成独立圆圈候选"'),
            panel.index("if scene.smrn_show_advanced:"),
        )

    def test_rotational_surface_rebuild_reprojects_only_green_source_mesh(self):
        adapter = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "surface_rebuild_blender.py").read_text(encoding="utf-8")
        operators = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "operators.py").read_text(encoding="utf-8")
        panel = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "panel.py").read_text(encoding="utf-8")
        self.assertIn("def _fit_rotational_from_selected_faces", adapter)
        self.assertIn("fit_rotational_surface(points, normals)", adapter)
        self.assertIn("def _rotational_target", adapter)
        self.assertIn('"exact_green_local_subdivision_radial_reprojection_v1"', adapter)
        self.assertIn('"whole_vehicle_search": False', adapter)
        self.assertIn('set() if mode in {"flatten", "rotational"}', adapter)
        self.assertIn('"unmarked_vertices_moved": 0', adapter)
        self.assertIn('"rotational_projection_complete"', adapter)
        self.assertIn('"rotational", "重建圆润原网面"', operators)
        self.assertIn('text="确认圆润并替换标记网面"', panel)
        self.assertNotIn('rebuild_rotational = rotational.operator(\n            "smrn.build_rotational_candidate"', panel)

    def test_visibility_guard_only_reveals_authoritative_objects(self):
        scene_state = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "scene_state.py").read_text(encoding="utf-8")
        visibility = scene_state.split("def keep_model_visible", 1)[1].split("def set_helpers_hidden", 1)[0]
        self.assertNotIn("model.all_objects", visibility)
        self.assertIn("if obj is None", visibility)
        self.assertIn("required_objects", visibility)
        self.assertIn("except (AttributeError, ReferenceError)", visibility)
        self.assertIn('obj.get("smrn_archive_only", False)', visibility)
        self.assertIn('obj.get("smrn_superseded_source_only", False)', visibility)
        self.assertIn("obj.hide_set(True)", visibility)

    def test_rotational_axis_candidates_are_data_derived(self):
        fitter = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "rotational_fit.py").read_text(encoding="utf-8")
        section = fitter.split("def candidate_axes", 1)[1].split("def _robust_linear", 1)[0]
        self.assertIn("centered_points", section)
        self.assertIn("centered_normals", section)
        self.assertNotIn("np.eye", section)

    def test_handle_feature_is_non_destructive_and_support_constrained(self):
        adapter = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "handle_blender.py").read_text(encoding="utf-8")
        fitter = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "handle_fit.py").read_text(encoding="utf-8")
        self.assertIn('CANDIDATE_PREFIX = "SMRN_HANDLE_CANDIDATE_"', adapter)
        self.assertIn("source_unchanged", adapter)
        self.assertNotIn("bpy.ops.object.delete", adapter)
        self.assertIn("_signed_angle", fitter)
        self.assertIn("support_angle_after_degrees", fitter)
        self.assertNotIn("np.eye", fitter)
        self.assertIn("terminal_bridge", adapter)
        self.assertIn('"path_bridge_samples": discarded_path_bridge_samples', adapter)
        self.assertIn(
            "discarded_topology_bridge_samples - discarded_path_bridge_samples",
            adapter,
        )
        self.assertIn("fit.half_span + endpoint_margin", adapter)
        self.assertIn("minimum_enclosing_circle", adapter)
        self.assertIn("_semantic_handle_faces", adapter)
        self.assertIn("np.sum(middle) < 1", fitter)
        self.assertIn('"global_geometry_scan": False', adapter)
        self.assertIn('bool(old_obj.get("smrn_accepted", False))', adapter)
        self.assertIn("def _evidence_request", adapter)
        self.assertIn("左右安装平面各补 1 个红色标记", adapter)
        self.assertIn("def _inferred_mount_surface", adapter)
        self.assertIn('"shared_leg_axis": True', adapter)
        self.assertIn('"uncovered": uncovered', adapter)
        self.assertTrue((ROOT / "scripts" / "live_handle_build_gate_test.py").is_file())

    def test_candidate_confirmation_and_local_thickness_workflow(self):
        operators = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "operators.py").read_text(encoding="utf-8")
        panel = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "panel.py").read_text(encoding="utf-8")
        adapter = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "handle_blender.py").read_text(encoding="utf-8")
        self.assertIn('bl_idname = "smrn.confirm_candidate"', operators)
        self.assertIn('clear_task_marks(context.scene)', operators)
        self.assertIn('obj["smrn_accepted"] = True', operators)
        self.assertIn('bpy.ops.wm.save_mainfile()', operators)
        self.assertIn('text="确认并清除标记"', panel)
        self.assertIn('text="粗细（1.00 = 刚好覆盖）"', panel)
        self.assertIn('def adjust_candidate_thickness(scene):', adapter)
        self.assertIn('"model_rescanned": False', adapter)

    def test_local_surface_rebuild_is_feature_locked_and_recoverable(self):
        adapter = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "surface_rebuild_blender.py").read_text(encoding="utf-8")
        operators = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "operators.py").read_text(encoding="utf-8")
        panel = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "panel.py").read_text(encoding="utf-8")
        addon = (ROOT / "blender_addon" / "semantic_mesh_marker_next" / "__init__.py").read_text(encoding="utf-8")
        self.assertIn('CANDIDATE_PREFIX = "SMRN_SURFACE_CANDIDATE_"', adapter)
        self.assertIn("obj.show_in_front = False", adapter)
        self.assertIn("preview.show_in_front = False", adapter)
        self.assertIn('"global_geometry_scan": False', adapter)
        self.assertIn('"selection_method": "exact_brushed_faces"', adapter)
        self.assertIn('"display_radius_used_for_growth": False', adapter)
        self.assertIn('def _normal_hint_from_records', adapter)
        self.assertIn('def _height_reference_from_records', adapter)
        self.assertIn('height_mode == "RED_REFERENCE"', adapter)
        self.assertIn('canvas_macro_folds if mode in {"canvas", "canvas_physics"}', adapter)
        self.assertIn('def _canvas_subdivision_cuts', adapter)
        self.assertIn('def _taubin_fair_canvas', adapter)
        self.assertIn('iterations=44', adapter)
        self.assertIn('facet_after_p95 <= math.radians(18.0)', adapter)
        self.assertIn('"canvas_base_faceting_reduced"', adapter)
        self.assertIn('"canvas_pipeline": (', adapter)
        self.assertIn('"fair_base_then_source_aligned_wave_outer_envelope_v3"', adapter)
        self.assertIn("def _canvas_outer_envelope_shift", adapter)
        self.assertIn('"canvas_outer_envelope_complete"', adapter)
        self.assertIn("def _canvas_final_dihedral_guard", adapter)
        self.assertIn('"post_wave_vs_current_faired_source_faceting_v1"', adapter)
        self.assertIn('"canvas_dihedral_guard_qa": canvas_dihedral_guard', adapter)
        self.assertIn('"current_green_region_only_no_vehicle_scan"', adapter)
        self.assertIn('"strict_green_surface_with_dense_outer_envelope"', adapter)
        self.assertIn("_set_current_mark_overlays_hidden(scene, True)", adapter)
        self.assertIn('polygon.use_smooth = bool(smooth_preview)', adapter)
        self.assertIn('"canvas", "canvas_physics", "rotational", "flatten"', adapter)
        self.assertIn('"confirmed_shading_matches_preview": True', adapter)
        self.assertIn('"smooth_shaded_region_faces": len(region_faces)', adapter)
        self.assertIn('"scope_policy": "strict_green_faces_only_v2"', adapter)
        self.assertIn('"strict_marked_scope": True', adapter)
        self.assertIn('"unmarked_vertices_moved": 0', adapter)
        self.assertIn('"method": "strict_single_plane_full_green_projection_v3"', adapter)
        self.assertIn("locked_vertices = set()", adapter)
        self.assertIn("locked_region_edges = set()", adapter)
        self.assertIn('"projected_vertices": len(region_vertices)', adapter)
        self.assertIn('"exact_tolerance": exact_tolerance', adapter)
        self.assertIn('"exact_planarity_passed": bool(', adapter)
        self.assertIn("def _apply_planar_custom_normals", adapter)
        self.assertIn('"custom_planar_normals_applied"', adapter)
        self.assertIn("def _show_exact_flatten_working_candidate", adapter)
        self.assertIn('working["smrn_mark_proxy_source"] = source.name', adapter)
        self.assertIn('working["smrn_mark_proxy_face_indices"] = face_indices_match', adapter)
        self.assertIn("def _restore_source_candidate_display", adapter)
        self.assertIn('source.display_type = "BOUNDS"', adapter)
        self.assertIn("matched_dihedral_edges", adapter)
        self.assertIn('"dihedral_sample_matched": True', adapter)
        self.assertIn('"dihedral_edges_before": len(matched_dihedral_edges)', adapter)
        self.assertIn('"dihedral_edges_after": len(matched_dihedral_edges)', adapter)
        self.assertNotIn("before_inner_edges", adapter)
        self.assertIn('"quality_gates": quality_gates', adapter)
        self.assertIn("preview_source_faces = set(region_faces)", adapter)
        self.assertNotIn("transition_ring_count = max(", adapter)
        self.assertIn('quality_gates["all_vertices_coplanar"] = bool(', adapter)
        self.assertIn('quality_gates["transition_topology_preserved"] = bool(', adapter)
        self.assertIn("def _face_shape_quality", adapter)
        self.assertIn("accepted_unstable_sliver_flips", adapter)
        self.assertIn("accepted_coherent_canvas_fold_rotations", adapter)
        self.assertIn('mode == "canvas_physics"', adapter)
        self.assertIn("normal_dot > -0.20", adapter)
        self.assertIn("positive_neighbors >= 3", adapter)
        self.assertIn('"canvas_physics": "多折面帆布重建"', adapter)
        self.assertIn("len(edge.link_faces) == 2", adapter)
        self.assertIn("sum(face in region_set for face in edge.link_faces) == 1", adapter)
        self.assertIn('if height_mode == "RED_REFERENCE":', adapter)
        self.assertIn('height_mode = "MEDIAN"', adapter)
        self.assertIn('if normal_mode == "RED_REFERENCE":', adapter)
        self.assertIn('normal_mode = "AUTO"', adapter)
        self.assertIn("strict_neighbor_majority", adapter)
        self.assertIn("positive_neighbors > len(neighbor_dots) * 0.5", adapter)
        self.assertIn("before_face_shape_quality.get(face, 1.0) <= 0.002", adapter)
        self.assertIn("source.data = new_mesh", adapter)
        self.assertIn("set_active_source(scene, source_snapshot(source))", adapter)
        self.assertIn("model.children.unlink(collection)", adapter)
        self.assertIn("candidates.children.link(collection)", adapter)
        self.assertIn("collection.hide_viewport = True", adapter)
        self.assertIn('bl_idname = "smrn.confirm_surface_replacement"', operators)
        self.assertIn('text="细化平滑"', panel)
        self.assertIn('text="一键平整"', panel)
        self.assertIn('text="0.50 = 旧版最高 · 1.00 = 强平滑"', panel)
        self.assertIn('max=1.0', addon)
        self.assertIn('smoothing_iterations = 2 + int(math.ceil(', adapter)
        self.assertIn('range(smoothing_iterations)', adapter)
        self.assertIn('"smoothing_iterations": smoothing_iterations', adapter)
        self.assertIn('"smrn_surface_height_mode"', panel)
        self.assertIn('"smrn_surface_normal_mode"', panel)
        self.assertIn('"flatten": "确认平整并清除标记"', panel)
        self.assertIn('"smooth": "确认平滑并清除标记"', panel)
        self.assertIn('text="帆布波浪重建"', panel)
        self.assertIn('"canvas": "确认帆布波浪并清除标记"', panel)
        self.assertIn('"canvas", "帆布波浪重建"', operators)
        self.assertIn('bpy.types.Scene.smrn_canvas_wave_strength', addon)
        self.assertIn('def _canvas_frame', adapter)
        self.assertIn('def _canvas_boundary_fades', adapter)
        self.assertIn('"random_displacement": False', adapter)
        self.assertIn('"whole_vehicle_search": False', adapter)
        self.assertIn('"fair_base_then_source_aligned_wave_outer_envelope_v3"', adapter)
        self.assertNotIn('"canvas_multifold"', operators)
        self.assertNotIn('"canvas_multifold"', adapter)
        self.assertNotIn('text="多折面帆布优化"', panel)
        self.assertIn('"canvas_physics", "多折面帆布重建（物理）"', operators)
        self.assertIn('text="多折面帆布重建（物理）"', panel)
        self.assertIn('"canvas_physics": "确认多折面帆布并清除标记"', panel)
        self.assertIn('def _physics_canvas_attachment_chain', adapter)
        self.assertIn('def _solve_physics_canvas', adapter)
        self.assertIn('"quasi_static_position_based_cloth_v2"', adapter)
        self.assertIn('def _physics_canvas_fold_guard', adapter)
        self.assertIn('"physics_cloth_coherent_fold_delta_v1"', adapter)
        self.assertIn('"two_stage_complete_surface_safe_fraction_line_search_v3"', adapter)
        self.assertIn('def _canvas_outer_envelope_after_safety', adapter)
        self.assertIn('"per_vertex_minimum_frame_normal_outer_correction_v2"', adapter)
        self.assertIn('"effective_deformation_scale"', adapter)
        self.assertIn('"phase": phase', adapter)
        self.assertIn('movable = sorted(region_vertices - locked_vertices', adapter)
        self.assertIn('bm.edges.ensure_lookup_table()', adapter)
        self.assertIn('bm.verts.index_update()', adapter)
        self.assertIn('def _locked_segment_memberships', adapter)
        self.assertIn('kdtree.KDTree', adapter)
        self.assertIn('constraint_passes = 2', adapter)
        self.assertIn('iterations = 28 + int(round(8.0 * bounded_strength))', adapter)
        self.assertIn('text="波浪程度"', panel)
        self.assertIn('不增加波纹数量', panel)
        self.assertIn('"scope_policy": "exact_green_faces_only_no_vehicle_scan"', adapter)
        self.assertIn('"whole_vehicle_search": False', adapter)
        self.assertIn('"dense_source_proximity_qa"', adapter)
        self.assertIn('bl_idname = "smrn.accept_current_surface"', operators)
        self.assertIn('self.report({"INFO"}, message)', operators)
        self.assertIn('text="确认当前效果并清除标记"', panel)
        self.assertIn('confirm_row.enabled = bool(counts[TARGET_ROLE] or counts[EXCLUDE_ROLE])', panel)
        self.assertIn("def _restore_normal_selection(context, source=None):", operators)
        self.assertIn("_restore_normal_selection(context, source)", operators)
        self.assertIn("if owns_token:", operators)
        self.assertIn("普通选择已恢复", operators)
        self.assertTrue((ROOT / "scripts" / "live_surface_confirm_ui_test.py").is_file())
        self.assertIn('mode == "flatten"', adapter)
        self.assertIn("strict_single_plane_full_green_projection_v3", adapter)
        self.assertIn("def _isolate_flatten_region_boundary", adapter)
        self.assertIn("detached_green_boundary_with_face_fan_sidewalls_v2", adapter)
        self.assertIn("duplicate_by_face[(vertex, face)] = copied", adapter)
        self.assertIn('"unmarked_vertices_moved": 0', adapter)
        self.assertIn('"flatten_boundary_isolation"', adapter)
        self.assertIn("def _region_face_components", adapter)
        self.assertIn('"flipped_faces"', adapter)
        self.assertIn('"degenerate_faces"', adapter)
        self.assertIn("def _candidate_request_signature", adapter)
        self.assertIn("def _matching_existing_candidate", adapter)
        self.assertIn('report["reused_existing"] = True', adapter)
        self.assertIn('scene["smrn_surface_last_report_json"] = json.dumps(', adapter)
        self.assertIn('"request_signature": request_signature', adapter)
        self.assertIn("已保留上一版候选", operators)
        self.assertIn("无需重复生成", operators)
        self.assertTrue((ROOT / "scripts" / "live_surface_repeat_click_test.py").is_file())


if __name__ == "__main__":
    unittest.main()
